config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  resources :users

  resources :events do
    member do
      post 'attend', to: 'events#attend'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "events#index"

  get 'users/show', to: 'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  validates :attendee_id, presence: true
  validates :attended_event_id, presence: true

  # Custom method to handle RSVP status, for example
  def accept_invitation
    update(rsvp_status: 'accepted')
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'

  validates :title, presence: true
  validates :event_date, presence: true

  has_many :attendances, foreign_key: 'attended_event_id'
  has_many :attendees, through: :attendances, source: :attendee
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, inverse_of: :creator

  # Attendeance model attrivutes
  has_many :attendances, foreign_key: 'attendee_id'
  has_many :attended_events, through: :attendances, source: :attended_event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password)}

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password)}
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @events = Event.order(event_date: :asc)
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    @event.user_id = current_user.id

    if @event.save
      redirect_to events_path
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    @attendances = User.joins(:attendances).where(attendances: { attended_event_id: params[:id]}).pluck(:username)
  end

  def attend
    @attendance = Attendance.new(attendee_id: current_user.id, attended_event_id: params[:id])
    if @attendance.save
      flash[:success] = "You've successfully joined the event!"
    else
      flash[:error] = "There was an error joining the event."
    end
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :event_date)
  end

  def set_event
    @event = Event.find(current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @events = Event.where(user_id: current_user.id)
    @attended_events = Event.joins(:attendances).where(attendances: { attendee_id: current_user.id}).order(event_date: :desc)
    puts "!!!!!!!!!!!!!"
    puts @attended_events
    puts "!!!!!!!!!!!!!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
 <% if user_signed_in? %>
    <div> Welcome <%= current_user.email %> </div> 
      <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
      <%= button_to "Show Posts", "/users/show", method: :get %>
  <% else %>
    <%= link_to 'Register', new_user_registration_path %>
    <%= button_to "Sign in", new_user_session_path %> 
  <% end %>

  <br>
  <h1>Create Event</h1>

  <%= form_with model: Event.new do |form| %>
    <div class="field">
      <%= form.label :title %><br />
      <%= form.text_field :title, placeholder: "Title" %>
    </div>

    <div class="field">
      <%= form.label :event_date %><br />
      <%= form.date_field :event_date %>
    </div>

    <%= submit_tag("Submit") %>
  <% end %>

  <h1>All Events!</h1>
  <% @events.each do |event| %>
    <div class="post">
      <div class="post-content">  
        <%= "Name: " + (User.find(event.user_id).username).to_s %> <br />
        <%= link_to(event.title, event_path(event)) %>
        <br>
        <%= "Date: " + event.event_date.to_s %>
      </div>
      <br>
    </div>
  <% end %>

app/views/events/show.html.erb
 <h1>Event Page</h1>
 
<div class="post">
  <div class="post-content">  
    <%= "Event: " + @event.title %>
    <br>
    <%= "Date: " + @event.event_date.to_s %>
  </div>
  <br>
</div>

<%= form_with model: @attendance, url: attend_event_path(@event) do |form| %>
  <%= form.submit "Attend" %>
<% end %>

<br />
<% @attendances.each do |name| %>
  <div class="attendances">
    <div class="name"> 
      <%= "Name: " + name %> <br />
    </div>
  </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
 <h1>My Events</h1>
 
 <% @events.each do |event| %>
    <div class="post">
      <div class="post-content">  
        <%= "Event: " + event.title %>
        <br>
        <%= "Date: " + event.event_date.to_s %>
      </div>
      <br>
    </div>
  <% end %>

  <br />

  <h1>Upcoming Events</h1>

  <% past_events_displayed = false %>
  <% @attended_events.each do |attend| %>
    <div class="attendances">
      <% if attend.event_date > Date.current %> 
        <div class="attendance-list">
          <%= "Title: " + attend.title %>
          <%= "Date: " + attend.event_date.to_s %>
        </div>
      <% else %>
        <% unless past_events_displayed %>
          <h1>Past Events</h1>
          <% past_events_displayed = true %>
        <% end %>
        <div class="attendance-list">
          <%= "Title: " + attend.title %>
          <%= "Date: " + attend.event_date.to_s %>
        </div>
      <% end %>
    </div>
  <% end %>
        